### ISSUE TITLE
Fix transformer blowing up when transforming imported variables

### ISSUE THREAD

**Issue by madou** [madou/untitled-css-in-js-project#23]
See: https://github.com/madou/untitled-css-in-js-project/pull/22

It's blowing up when iterating through the JSX attributes (`className` doesn't have a parent = blows up).

Need to understand why - if it's a bug - and if we can work around it. It works fine in tests - blows up when running storybook/webpack/ts-loader though.

---

Found this https://github.com/longlho/ts-transform-css-modules - should be good reference.

Edit: Or not because it follows css files not typescript. Meh.

**Comment by madou** [comment]
Okay after playing with it I've gotten a different error message when adding parents properly to the `className` attributes (and its identifier.. and value..)

I'm probably missing more parents somewhere. This is kind of silly though :) why doesn't it add parents automatically?

**Comment by marionebl** [comment]
For some of the things you try to do you might have better results with the typechecker API (`program.getTypeChecker`)

**Comment by madou** [comment]
@marionebl i found if i run the transformed file through `ts.bindSourceFile(completedNode, context.getCompilerOptions());` it gets it through the transform but then the imports aren't in scope anymore (they're just not there - best guess is TS things they're not used anymore and gets rid of them?

do you have any experience with accessing variables through module boundaries? atm it looks like i need to run `transpileOnly: false` to get TS to actually resolve the imports - and if i do that i run into all of these problems

**Comment by marionebl** [comment]
> do you have any experience with accessing variables through module boundaries? atm it looks like i need to run transpileOnly: false to get TS to actually resolve the imports - and if i do that i run into all of these problems

Yes we did that quite a lot when working on the analyzer for Alva: https://github.com/meetalva/alva/tree/master/packages/analyzer/src. If I recall correctly we took a lot of inspiration from the way `ts-morph` does it:

https://github.com/dsherret/ts-morph/blob/439a0d5372810b9636c58e711f7454edeae16862/packages/ts-morph/src/utils/compiler/ModuleUtils.ts#L13

**Comment by madou** [comment]
@marionebl hey so in tests this works but in storybook it blows up. any chance you can help me debug it?

```
git checkout test-dont-merge-to-master
yarn test src/ts-transformer/__tests__/index.test.tsx --watch # all pass
yarn start # blows up
```

need to know

1. how can we replicate this blow up in tests
2. how to fix it. like just importing a module and logging it makes the transformer blow up

```ts
/** @jsx jsx */
import { jsx } from '../src';
import { hover } from './mixins/mixins';

console.log(hover);

export const objectLiteralImportedObj = () => {
  return (
    <div
      css={{
        display: 'flex',
        fontSize: '50px',
        color: 'blue',
      }}>
      Hello, world!
    </div>
  );
};
```

```sh
/Users/mdougall/projects/untitled-css-in-js-project/node_modules/typescript/lib/typescript.js:95861
                throw e;
                ^

TypeError: Cannot read property 'kind' of undefined
    at Object.isAssertionExpression (/Users/mdougall/projects/untitled-css-in-js-project/node_modules/typescript/lib/typescript.js:16303:25)
...
```

**Comment by marionebl** [comment]
Had a quick go at this, as of yet I could not reproduce the issue outside of `webpack`, even when changing gears to `@ts-morph/bootstrap` instead of `ts-transformer-testing-library`.

I think there is merit to the hunch this is related to the typechecking phase - disabling it again via `transpileOnly` hides the issue. Also this happens in a code path below `getDiagnostics > checkSourceFile`. Maybe this is related to something wonky `ts-loader` does during the typechecking phase?
 
Next I'll try to get plain `ttsc` to break for the example.

**Comment by madou** [comment]
@marionebl i think you're onto something. i used https://github.com/s-panferov/awesome-typescript-loader instead of ts-loader and it.. works! WITH the import!

get the latest of `test-dont-merge-to-master` and do `yarn start`

**Comment by marionebl** [comment]
Great news! I dug a little deeper and I think the statement that causes `ts-loader` to throw up is this:

https://github.com/madou/untitled-css-in-js-project/blob/adf67b74158846d77ed8ef68d9643d55db81d798/src/ts-transformer/css-prop/visitors/visit-jsx-element-with-css-prop.tsx#L72-L74

Apparently the generated code is typechecked again, which causes the created synthetic node to fail...

**Comment by madou** [comment]
Oh that's interesting. I don't think this should happen right? Type
checking after transforming

**Comment by marionebl** [comment]
Yes, can't see how that would make sense. I suspect mutating the original node might cause some kind of concurrency issue with `ts-loader`? Just speculation though at this point.

**Comment by marionebl** [comment]
I experimented with switching back to immutable ts API and apparently `ts-loader` likes this better. As for testing I suspect we'd have to introduce rather heavy integration tests that use webpack and ts-loader and check if the compilation works :/

**Comment by madou** [comment]
cheers @marionebl 

would you be able to raise a bug on ts-loader with this info? you've been such a great help thank so much - just merged the fix to master

**Comment by marionebl** [comment]
> would you be able to raise a bug on ts-loader with this info? you've been such a great help thank so much - just merged the fix to master

sure, will do that tomorrow!
